SOURCE_PREFIX=$HOME/src
INSTALL_PREFIX=$HOME/usr

PATH=$INSTALL_PREFIX/bin:$PATH
LD_LIBRARY_PATH=$INSTALL_PREFIX/lib:$LD_LIBRARY_PATH
LIBRARY_PATH=$INSTALL_PREFIX/lib:$LIBRARY_PATH
CPLUS_INCLUDE_PATH=$INSTALL_PREFIX/include:$CPLUS_INCLUDE_PATH
C_INCLUDE_PATH=$INSTALL_PREFIX/include:$C_INCLUDE

PYTHONHOME=$INSTALL_PREFIX
PYTHONPATH=$INSTALL_PREFIX/lib/python2.7:$PYTHONPATH
